module_name: "example_dam"


buckets:
    bucket_1:
        id: 1
        frequency_hz: 10
        parameters:
            - dam_chan_1
            - dam_chan_2
            - dam_chan_3
            - dam_chan_4
            - dam_chan_5
            - dam_chan_6
            - dam_chan_7
            - dam_chan_8

    bucket_2:
        id: 2
        frequency_hz: 10
        parameters:        
            - dam_chan_9
            - dam_chan_10
            - dam_chan_11
            - dam_chan_12
            - dam_chan_13
            - dam_chan_14
            - dam_chan_15
            - dam_chan_16
            
    bucket_3:
        id: 3
        frequency_hz: 10
        parameters:
            - dam_chan_17
            - dam_chan_18
            - dam_chan_19
            - dam_chan_20
            - dam_chan_21
            - dam_chan_22
            - dam_chan_23
            - dam_chan_24
            
    bucket_4:
        id: 4
        frequency_hz: 1
        parameters:
            - float_tester
            - float_tester_2
            - float_tester_3
            - float_tester_4


parameters_produced:
    dam_chan_1:
        produced_by: ADC3_IN9
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_2:
        produced_by: ADC3_IN14
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
    dam_chan_3:
        produced_by: ADC3_IN15
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10

    dam_chan_4:
        produced_by: ADC3_IN4
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
    dam_chan_5:
        produced_by: ADC3_IN5
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
    dam_chan_6:
        produced_by: ADC3_IN6
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10

    dam_chan_7:
        produced_by: ADC3_IN7
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_8:
        produced_by: ADC3_IN8
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_9:
        produced_by: ADC2_IN10
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_10:
        produced_by: ADC2_IN11
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_11:
        produced_by: ADC2_IN12
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
    dam_chan_12:
        produced_by: ADC2_IN13
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_13:
        produced_by: ADC2_IN0
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_14:
        produced_by: ADC2_IN1
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_15:
        produced_by: ADC2_IN2
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_16:
        produced_by: ADC2_IN3
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_17:
        produced_by: ADC1_IN4
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_18:
        produced_by: ADC1_IN5
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_19:
        produced_by: ADC1_IN6
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_20:
        produced_by: ADC1_IN7
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_21:
        produced_by: ADC1_IN14
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_22:
        produced_by: ADC1_IN15
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_23:
        produced_by: ADC1_IN8
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    dam_chan_24:
        produced_by: ADC1_IN9
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10

# CAN sensors:
    float_tester:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: d16_fixed
        num_samples_buffered: 1
            
    float_tester_2:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: u16_raw
        num_samples_buffered: 1
            
    float_tester_3:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: float_1_raw
        num_samples_buffered: 1
            
    float_tester_4:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: float_2_scaled
        num_samples_buffered: 1

