module_name: "example_dam"


buckets:
    bucket_1:
        id: 1
        frequency_hz: 50
        parameters:
            - adc1_tester_0
            - adc1_tester_1
            - adc1_tester_2
            - adc1_tester_3
            - adc1_tester_4
            - adc1_tester_5

    bucket_2:
        id: 2
        frequency_hz: 50
        parameters:
            - adc2_tester_0
            - adc2_tester_1
            - adc2_tester_2
            - adc2_tester_3
            - adc2_tester_4
            
    bucket_3:
        id: 3
        frequency_hz: 50
        parameters:
            - adc3_tester_0
            - adc3_tester_1
            - adc3_tester_2
            - adc3_tester_3
            - adc3_tester_4
            - adc3_tester_5
            - adc3_tester_6
            - adc3_tester_7
            - adc3_tester_8
            - adc3_tester_9
            - adc3_tester_10
            - adc3_tester_11

    bucket_4:
        id: 4
        frequency_hz: 1
        parameters:
            - float_tester_4
            - float_tester_5
            - float_tester_6
            - example_new_param

parameters_produced:
# ADC1:
    adc1_tester_0:
        produced_by: ADC1_IN0
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 100
        
    adc1_tester_1:
        produced_by: ADC1_IN1
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
    adc1_tester_2:
        produced_by: ADC1_IN2
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10

    adc1_tester_3:
        produced_by: ADC1_IN3
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
    adc1_tester_4:
        produced_by: ADC1_IN4
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
    adc1_tester_5:
        produced_by: ADC1_IN5
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10

# ADC2:
    adc2_tester_0:
        produced_by: ADC2_IN6
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc2_tester_1:
        produced_by: ADC2_IN7
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc2_tester_2:
        produced_by: ADC2_IN9
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc2_tester_3:
        produced_by: ADC2_IN14
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc2_tester_4:
        produced_by: ADC2_IN15
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
# ADC3:
    adc3_tester_0:
        produced_by: ADC3_IN4
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_1:
        produced_by: ADC3_IN5
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_2:
        produced_by: ADC3_IN6
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_3:
        produced_by: ADC3_IN7
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_4:
        produced_by: ADC3_IN8
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_5:
        produced_by: ADC3_IN9
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_6:
        produced_by: ADC3_IN10
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_7:
        produced_by: ADC3_IN11
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_8:
        produced_by: ADC3_IN12
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_9:
        produced_by: ADC3_IN13
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_10:
        produced_by: ADC3_IN14
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
    adc3_tester_11:
        produced_by: ADC3_IN15
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10

# CAN sensors:
    float_tester_4:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: d16_fixed
        num_samples_buffered: 1
            
    float_tester_5:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: u16_raw
        num_samples_buffered: 1
            
    float_tester_6:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: float_1_raw
        num_samples_buffered: 1
            
    example_new_param:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: float_2_scaled
        num_samples_buffered: 1

