
module_name: "example_dam"

buckets:
    high_frequency_tcm:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 250
        parameters:
            # these must directly be a variable defined in GopherCAN
            rear_left_shock_pot:
                ADC: ADC1_IN2
                sensor: linear_pos_sensor_25
                samples_buffered: 1
            rear_right_shock_pot:
                ADC: ADC1_IN3
                sensor: linear_pos_sensor_25
                samples_buffered: 1
            front_left_shock_pot:
                ADC: ADC2_IN2
                sensor: linear_pos_sensor_25
                samples_buffered: 1
            front_right_shock_pot:
                ADC: ADC2_IN3
                sensor: linear_pos_sensor_25
                samples_buffered: 1
            engine_temp_ecu:
                ADC: ADC3_IN2
                sensor: temp_sensor
                samples_buffered: 1
            oil_temp_ecu:
                ADC: ADC3_IN1
                sensor: temp_sensor
                samples_buffered: 1
            
    low_frequency_tcm:
        frequency_hz: 100
        parameters:
            tcm_shifter_position:
                ADC: ADC2_IN11
                sensor: linear_pos_sensor_50
                samples_buffered: 1
            tcm_clutch_position:
                ADC: ADC1_IN10
                sensor: linear_pos_sensor_50
                samples_buffered: 1
            tcm_neutral:
                # NON_ADC sensors means the value is produced somewhere in the main software then put into the GopherCAN value manually
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcm_target_rpm:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcm_current_gear:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcm_target_gear:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcm_currently_moving:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcm_successful_shift:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcm_trans_rpm:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcm_lap_timer:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcm_using_clutch:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcm_anti_stall:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1


