module_name: "example_dam"


buckets:
    bucket_1:
        id: 1
        frequency_hz: 100
        parameters:
            - tire_temp_rr_1
            - tire_temp_rr_2

    bucket_2:
        id: 2
        frequency_hz: 100
        parameters:
            - tire_temp_rr_3
            - tire_temp_rr_4
            - tire_temp_rr_5
            - tire_temp_rr_6
            - tire_temp_rr_7
            - tire_temp_rr_8
            - tire_temp_rr_9
            - tire_temp_rr_10
            - tire_temp_rr_11
            - tire_temp_rr_12
            - tire_temp_rr_13
            - tire_temp_rr_14
            - tire_temp_rr_15
            - tire_temp_rr_16
            
    bucket_3:
        id: 3
        frequency_hz: 100
        parameters:
            - tire_temp_rl_1
            - tire_temp_rl_2
            - tire_temp_rl_3
            - tire_temp_rl_4
            - tire_temp_rl_5
            - tire_temp_rl_6
            - tire_temp_rl_7
            - tire_temp_rl_8
            
    bucket_4:
        id: 4
        frequency_hz: 100
        parameters:
            - tire_temp_rl_9
            - tire_temp_rl_10
            - tire_temp_rl_11
            - tire_temp_rl_12

parameters_produced:
# DAM CHANNEL 1
    tire_temp_rr_1:
        produced_by: ADC3_IN9
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
       
# DAM CHANNEL 2       
    tire_temp_rr_2:
        produced_by: ADC3_IN14
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
# DAM CHANNEL 3
    tire_temp_rr_3:
        produced_by: ADC3_IN15
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 4
    tire_temp_rr_4:
        produced_by: ADC3_IN4
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
           
# DAM CHANNEL 5           
    tire_temp_rr_5:
        produced_by: ADC3_IN5
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
# DAM CHANNEL 6
    tire_temp_rr_6:
        produced_by: ADC3_IN6
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 7
    tire_temp_rr_7:
        produced_by: ADC3_IN7
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 8
    tire_temp_rr_8:
        produced_by: ADC3_IN8
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 9
    tire_temp_rr_9:
        produced_by: ADC2_IN10
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 10
    tire_temp_rr_10:
        produced_by: ADC2_IN11
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 11
    tire_temp_rr_11:
        produced_by: ADC2_IN12
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
# DAM CHANNEL 12
    tire_temp_rr_12:
        produced_by: ADC2_IN13
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 13
    tire_temp_rr_13:
        produced_by: ADC2_IN0
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 14
    tire_temp_rr_14:
        produced_by: ADC2_IN1
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 15
    tire_temp_rr_15:
        produced_by: ADC2_IN2
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 16
    tire_temp_rr_16:
        produced_by: ADC2_IN3
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 17
    tire_temp_rl_1:
        produced_by: ADC1_IN4
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 18
    tire_temp_rl_2:
        produced_by: ADC1_IN5
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 19
    tire_temp_rl_3:
        produced_by: ADC1_IN6
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 20
    tire_temp_rl_4:
        produced_by: ADC1_IN7
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 21
    tire_temp_rl_5:
        produced_by: ADC1_IN14
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 22
    tire_temp_rl_6:
        produced_by: ADC1_IN15
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 23
    tire_temp_rl_7:
        produced_by: ADC1_IN8
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 24
    tire_temp_rl_8:
        produced_by: ADC1_IN9
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10

# CAN sensors:
    tire_temp_rl_9:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: d16_fixed
        num_samples_buffered: 1
            
    tire_temp_rl_10:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: u16_raw
        num_samples_buffered: 1
            
    tire_temp_rl_11:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: float_1_raw
        num_samples_buffered: 1
            
    tire_temp_rl_12:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: float_2_scaled
        num_samples_buffered: 1

