module_name: "rear_dam"


buckets:
    bucket_1:
        id: 1
        frequency_hz: 25
        parameters:
            - ride_height_rear
            - brake_pressure_rear 
            - rear_right_shock_pot
            - rear_left_shock_pot
            - right_rad_pressure_in
            - right_rad_pressure_out
            - right_rad_pressure_drop
            - right_rad_temp_in
            - right_rad_temp_out
            - left_rad_pressure_in
            - left_rad_pressure_out
            - left_rad_pressure_drop
            - left_rad_temp_in
            - left_rad_temp_out
            - air_tank_pressure
            - pnumatic_line_pressure
            - water_pump_pressure_in
            - water_pump_pressure_out
            - main_circuit_flow_rate
            - exhaust_temp_1
            - exhaust_temp_2
            - exhaust_temp_3
            - exhaust_temp_4
            - exhaust_temp_5
            - lambda_header_1
            - lambda_header_2
            - oil_cooler_temp_in
            - oil_cooler_temp_out
            - oil_cooler_pressure_in
            - oil_cooler_pressure_out
            
    tire_brake_temps:
        id: 2
        frequency_hz: 5
        parameters:
            # brake temps
            - brake_temp_rr_1
            - brake_temp_rr_2
            - brake_temp_rr_3
            - brake_temp_rr_4
            - brake_temp_rr_5
            - brake_temp_rr_6
            - brake_temp_rr_7
            - brake_temp_rr_8
            - brake_temp_rr_9
            - brake_temp_rr_10
            - brake_temp_rr_11
            - brake_temp_rr_12
            - brake_temp_rr_13
            - brake_temp_rr_14
            - brake_temp_rr_15
            - brake_temp_rr_16
            - brake_temp_rl_1
            - brake_temp_rl_2
            - brake_temp_rl_3
            - brake_temp_rl_4
            - brake_temp_rl_5
            - brake_temp_rl_6
            - brake_temp_rl_7
            - brake_temp_rl_8
            - brake_temp_rl_9
            - brake_temp_rl_10
            - brake_temp_rl_11
            - brake_temp_rl_12
            - brake_temp_rl_13
            - brake_temp_rl_14
            - brake_temp_rl_15
            - brake_temp_rl_16

            # tire temps
            - tire_temp_rr_1
            - tire_temp_rr_2
            - tire_temp_rr_3
            - tire_temp_rr_4
            - tire_temp_rr_5
            - tire_temp_rr_6
            - tire_temp_rr_7
            - tire_temp_rr_8
            - tire_temp_rr_9
            - tire_temp_rr_10
            - tire_temp_rr_11
            - tire_temp_rr_12
            - tire_temp_rr_13
            - tire_temp_rr_14
            - tire_temp_rr_15
            - tire_temp_rr_16
            - tire_temp_rl_1
            - tire_temp_rl_2
            - tire_temp_rl_3
            - tire_temp_rl_4
            - tire_temp_rl_5
            - tire_temp_rl_6
            - tire_temp_rl_7
            - tire_temp_rl_8
            - tire_temp_rl_9
            - tire_temp_rl_10
            - tire_temp_rl_11
            - tire_temp_rl_12
            - tire_temp_rl_13
            - tire_temp_rl_14
            - tire_temp_rl_15
            - tire_temp_rl_16


parameters_produced:
# DAM CHANNEL 1
    rear_right_shock_pot:
        produced_by: ADC3_IN9
        sensor:
            name: "linear_pos_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 2
    right_rad_pressure_out:
        produced_by: ADC3_IN14
        sensor:
            name: "pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 3
    right_rad_temp_in:
        produced_by: ADC3_IN15
        sensor:
            name: "temp_sensor"
            output: resistance
        num_samples_buffered: 10

# DAM CHANNEL 4
    right_rad_pressure_in:
        produced_by: ADC3_IN4
        sensor:
            name: "pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 5
    right_rad_pressure_drop:
        produced_by: ADC3_IN5
        sensor:
            name: "pressure_drop_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 6
    air_tank_pressure:
        produced_by: ADC3_IN6
        sensor:
            name: "MSP300"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 7
    main_circuit_flow_rate:
        produced_by: ADC3_IN7
        sensor:
            name: "water_flow_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 8
    water_pump_pressure_in:
        produced_by: ADC3_IN8
        sensor:
            name: "pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 9
    water_pump_pressure_out:
        produced_by: ADC2_IN10
        sensor:
            name: "pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 10
    pnumatic_line_pressure:
        produced_by: ADC2_IN11
        sensor:
            name: "pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 11
    right_rad_temp_out:
        produced_by: ADC2_IN12
        sensor:
            name: "temp_sensor"
            output: resistance
        num_samples_buffered: 10

# DAM CHANNEL 12
    rear_left_shock_pot:
        produced_by: ADC2_IN13
        sensor:
            name: "linear_pos_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 13
    left_rad_pressure_drop:
        produced_by: ADC2_IN0
        sensor:
            name: "pressure_drop_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 14
    left_rad_pressure_in:
        produced_by: ADC2_IN1
        sensor:
            name: "pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 15
    left_rad_pressure_out:
        produced_by: ADC2_IN2
        sensor:
            name: "pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 16
    left_rad_temp_in:
        produced_by: ADC2_IN3
        sensor:
            name: "temp_sensor"
            output: resistance
        num_samples_buffered: 10

# DAM CHANNEL 17
    left_rad_temp_out:
        produced_by: ADC1_IN4
        sensor:
            name: "temp_sensor"
            output: resistance
        num_samples_buffered: 10

# DAM CHANNEL 18
    oil_cooler_pressure_in:
        produced_by: ADC1_IN5
        sensor:
            name: "pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 19
    oil_cooler_pressure_out:
        produced_by: ADC1_IN6
        sensor:
            name: "pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 20
    ride_height_rear:
        produced_by: ADC1_IN7
        sensor:
            name: "ride_height"
            output: voltage
        num_samples_buffered: 10

# DAM CHANNEL 21
    oil_cooler_temp_in:
        produced_by: ADC1_IN14
        sensor:
            name: "temp_sensor"
            output: resistance
        num_samples_buffered: 10

# DAM CHANNEL 22
    oil_cooler_temp_out:
        produced_by: ADC1_IN15
        sensor:
            name: "temp_sensor"
            output: resistance
        num_samples_buffered: 10

# DAM CHANNEL 23
    brake_pressure_rear:
        produced_by: ADC1_IN8
        sensor:
            name: "brake_pressure_sensor"
            output: voltage
        num_samples_buffered: 10

# CAN sensors:    
    exhaust_temp_1:
        produced_by: CAN
        sensor:
            name: "exhaust_gas_temp"
            output: TODO
        num_samples_buffered: 1
        
    exhaust_temp_2:
        produced_by: CAN
        sensor:
            name: "exhaust_gas_temp"
            output: TODO
        num_samples_buffered: 1

    exhaust_temp_3:
        produced_by: CAN
        sensor:
            name: "exhaust_gas_temp"
            output: TODO
        num_samples_buffered: 1
        
    exhaust_temp_4:
        produced_by: CAN
        sensor:
            name: "exhaust_gas_temp"
            output: TODO
        num_samples_buffered: 1
        
    exhaust_temp_5:
        produced_by: CAN
        sensor:
            name: "exhaust_gas_temp"
            output: TODO
        num_samples_buffered: 1
        
    lambda_header_1:
        produced_by: CAN
        sensor:
            name: "lambda_sensor"
            output: TODO
        num_samples_buffered: 1
        
    lambda_header_2:
        produced_by: CAN
        sensor:
            name: "lambda_sensor"
            output: TODO
        num_samples_buffered: 1

    brake_temp_rr_1:
        produced_by: CAN
        sensor:
            name: "brake_temp_sensor"
            output: rear_right_1
        num_samples_buffered: 1
    # TODO there needs to be 31 more
    
    tire_temp_rr_1:
        produced_by: CAN
        sensor:
            name: "tire_temp_sensor"
            output: rear_right_1
        num_samples_buffered: 1
    # TODO there needs to be 31 more