module_name: "front_dam"


buckets:
    shock_pots:
        id: 1
        frequency_hz: 100
        parameters:
            - front_left_shock_pot
            - front_right_shock_pot
    
    bucket_1:
        id: 2
        frequency_hz: 100
        parameters:
            - steering_angle
            - brake_temp_fl
            - brake_temp_fr
            - brake_pressure_rear
            - firewall_temp
            - ride_height_front
            # 5 axis
            - yaw_rate
            - y_axis_accel
            - roll_rate
            - x_axis_accel
            - z_axis_accel


parameters_produced:
# DAM CHANNEL 1
    front_left_shock_pot:
        produced_by: ADC3_IN9
        sensor:
            name: "linear_pos_sensor_25"
            output: voltage
        num_samples_buffered: 1
       
# DAM CHANNEL 2       
    front_right_shock_pot:
        produced_by: ADC3_IN14
        sensor:
            name: "linear_pos_sensor_25"
            output: voltage
        num_samples_buffered: 1
            
# DAM CHANNEL 3
    steering_angle:
        produced_by: ADC3_IN15
        sensor:
            name: "steering_angle_sensor"
            output: voltage
        num_samples_buffered: 1
           
# DAM CHANNEL 4        
    brake_temp_fl:
        produced_by: ADC3_IN4
        sensor:
            name: "brake_temp_sensor"
            output: voltage
        num_samples_buffered: 1
        
# DAM CHANNEL 5
    brake_temp_fr:
        produced_by: ADC3_IN5
        sensor:
            name: "brake_temp_sensor"
            output: voltage
        num_samples_buffered: 1
        
# DAM CHANNEL 6
    brake_pressure_rear:
        produced_by: ADC3_IN6
        sensor:
            name: "brake_pressure_sensor"
            output: voltage
        num_samples_buffered: 10
        
# DAM CHANNEL 8
    firewall_temp:
        produced_by: ADC3_IN8
        sensor:
            name: "temp_sensor"
            output: resistance
        num_samples_buffered: 1
        
# DAM CHANNEL 10
    ride_height_front:
        produced_by: ADC2_IN11
        sensor:
            name: "ride_hight_sensor"
            output: voltage
        num_samples_buffered: 1

# CAN sensors:
    yaw_rate:
        produced_by: CAN
        sensor:
            name: "five_axis"
            output: yaw_rate
        num_samples_buffered: 1
        
    y_axis_accel:
        produced_by: CAN
        sensor:
            name: "five_axis"
            output: y_axis_accel
        num_samples_buffered: 1
        
    roll_rate:
        produced_by: CAN
        sensor:
            name: "five_axis"
            output: roll_rate
        num_samples_buffered: 1
        
    x_axis_accel:
        produced_by: CAN
        sensor:
            name: "five_axis"
            output: x_axis_accel
        num_samples_buffered: 1
        
    z_axis_accel:
        produced_by: CAN
        sensor:
            name: "five_axis"
            output: z_axis_accel
        num_samples_buffered: 1

