module_name: "PDM"


buckets:
    bucket_1:
        id: 1
        frequency_hz: 3
        parameters:
            - pdm_0_current
            - pdm_1_current
            - pdm_2_current
            - pdm_3_current
            - pdm_4_current
            - pdm_5_current
            - pdm_6_current
            - pdm_7_current
            - pdm_8_current
            - pdm_9_current
            - pdm_10_current
            
            - pdm_11_current
            - pdm_12_current
            - pdm_13_current
            - pdm_14_current
            - pdm_15_current
            - pdm_16_current
            - pdm_17_current
            - pdm_18_current
            - pdm_19_current
            
            

parameters_produced:
# ADC1:
    pdm_0_current:
        produced_by: ADC1_IN0
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50
        
    pdm_1_current:
        produced_by: ADC1_IN1
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50
        
    pdm_2_current:
        produced_by: ADC1_IN2
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50
    
    pdm_3_current:
        produced_by: ADC1_IN3
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_4_current:
        produced_by: ADC1_IN4
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_5_current:
        produced_by: ADC1_IN5
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_6_current:
        produced_by: ADC1_IN6
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_7_current:
        produced_by: ADC1_IN7
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_8_current:
        produced_by: ADC1_IN12
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_9_current:
        produced_by: ADC1_IN13
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50
#ADC3

    pdm_10_current:
        produced_by: ADC3_IN4
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_11_current:
        produced_by: ADC3_IN5
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_12_current:
        produced_by: ADC3_IN6
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_13_current:
        produced_by: ADC3_IN7
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_14_current:
        produced_by: ADC3_IN8
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_15_current:
        produced_by: ADC3_IN9
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_16_current:
        produced_by: ADC3_IN10
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_17_current:
        produced_by: ADC3_IN11
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_18_current:
        produced_by: ADC3_IN14
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50

    pdm_19_current:
        produced_by: ADC3_IN15
        sensor:
            name: "pdm_current_sensor"
            output: voltage
        num_samples_buffered: 50
        
        